export const DOC_DEFININITION_STYLE = {
  'html-p': {
    fontSize: 10,
    bold: false,
    margin: [0, 0, 0, 0],
    alignment: 'justify',
  },
  'html-text': {
    fontSize: 10,
    bold: false,
    margin: [0, 0, 0, 0],
    alignment: 'justify',
    lineHeight: 1,
  },
  'html-title': {
    fontSize: 12,
    bold: true,
    margin: 0,
    alignment: 'center',
    lineHeight: 0.15,
  },
  'html-subtitle': {
    fontSize: 10,
    bold: false,
    margin: 0,
    alignment: 'center',
    color: '#5b5b5b',
    lineHeight: 0.15,
  },
  'html-th': {
    fontSize: 10,
    bold: true,
    margin: [0, 0, 0, 0],
    alignment: 'center',
  },
  'table-cell': {
    fontSize: 10,
    bold: true,
    margin: 0,
    alignment: 'left',
  },
  'table-cell-bold': {
    fontSize: 10,
    bold: true,
    margin: 0,
    alignment: 'center',
  },
  'table-cell-regular': {
    fontSize: 10,
    bold: false,
    margin: 0,
    alignment: 'left',
  },
  'table-cell-sum': {
    fontSize: 10,
    bold: true,
    margin: 0,
    alignment: 'right',
  },
  'table-footer-cell-label': {
    fontSize: 12,
    bold: true,
    margin: [0, 0, 0, 0],
    alignment: 'right',
  },
  'table-footer-cell-sum': {
    fontSize: 12,
    bold: true,
    margin: [0, 0, 0, 0],
    alignment: 'right',
  },
  'html-note': {
    fontSize: 10,
    bold: false,
    margin: [40, 0, 20, 0],
    alignment: 'left',
  },
  'html-requisites-sign': {
    fontSize: 10,
    bold: false,
    margin: [100, 0, 20, 0],
    alignment: 'right',
    italics: true,
  },
  'html-requisites': {
    fontSize: 10,
    bold: false,
    margin: 0,
    alignment: 'justify',
    italics: false,
    color: '#5b5b5b',
    lineHeight: 1.2,
  },
  'html-requisites-title': {
    fontSize: 11,
    bold: true,
    margin: [20, 0, 20, 0],
    alignment: 'left',
    italics: false,
    color: '#000',
  },
};
